{% set name = "rsc-2fa" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rsc/2fa/archive/v{{ version }}.tar.gz
  sha256: d8db6b9a714c9146a4b82fd65b54f9bdda3e58380bce393f45e1ef49e4e9bee5

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - m2-grep  # [win]
  commands:
    - 2fa --help 2>&1 | grep -q "2fa -list"

about:
  home: https://github.com/rsc/rsc-2fa
  license: BSD-3-Clause
  license_file: 
    - LICENSE
    - license-files/
  summary: Two-factor authentication on the command-line
  dev_url: https://github.com/rsc/rsc-2fa

extra:
  recipe-maintainers:
    - danielnachun
